export const products = [
    {
      id: 1,
      name: "Wireless Headphones",
      price: 99.99,
      category: "Electronics",
      rating: 4.5,
      image: "https://via.placeholder.com/400x300?text=Wireless+Headphones",
    },
    {
      id: 2,
      name: "Smart Watch",
      price: 199.99,
      category: "Wearables",
      rating: 4.8,
      image: "https://via.placeholder.com/400x300?text=Smart+Watch",
    },
    {
      id: 3,
      name: "Gaming Keyboard",
      price: 162.63,
      category: "Gaming",
      rating: 1.7,
      image: "https://via.placeholder.com/400x300?text=Gaming+Keyboard",
    },
    {
      id: 4,
      name: "Vacuum Cleaner",
      price: 984.4,
      category: "Home Appliances",
      rating: 2.9,
      image: "https://via.placeholder.com/400x300?text=Vacuum+Cleaner",
    },
    {
      id: 5,
      name: "Microwave",
      price: 449.18,
      category: "Home Appliances",
      rating: 1.7,
      image: "https://via.placeholder.com/400x300?text=Microwave",
    },
    {
      id: 6,
      name: "Bluetooth Speaker",
      price: 458.17,
      category: "Electronics",
      rating: 2.8,
      image: "https://via.placeholder.com/400x300?text=Bluetooth+Speaker",
    },
    {
      id: 7,
      name: "Smartphone",
      price: 634.99,
      category: "Electronics",
      rating: 3.9,
      image: "https://via.placeholder.com/400x300?text=Smartphone",
    },
    {
      id: 8,
      name: "Smart Glasses",
      price: 82.22,
      category: "Wearables",
      rating: 2.1,
      image: "https://via.placeholder.com/400x300?text=Smart+Glasses",
    },
    {
      id: 9,
      name: "Fitness Tracker",
      price: 379.31,
      category: "Wearables",
      rating: 3.3,
      image: "https://via.placeholder.com/400x300?text=Fitness+Tracker",
    },
    {
      id: 10,
      name: "Air Conditioner",
      price: 236.09,
      category: "Home Appliances",
      rating: 4.1,
      image: "https://via.placeholder.com/400x300?text=Air+Conditioner",
    },
    {
      id: 11,
      name: "Laptop",
      price: 713.88,
      category: "Electronics",
      rating: 2.3,
      image: "https://via.placeholder.com/400x300?text=Laptop",
    },
    {
      id: 12,
      name: "Gaming Chair",
      price: 205.73,
      category: "Gaming",
      rating: 2.1,
      image: "https://via.placeholder.com/400x300?text=Gaming+Chair",
    },
    {
      id: 13,
      name: "Refrigerator",
      price: 662.76,
      category: "Home Appliances",
      rating: 1.8,
      image: "https://via.placeholder.com/400x300?text=Refrigerator",
    },
    {
      id: 14,
      name: "Gaming Console",
      price: 173.65,
      category: "Gaming",
      rating: 3.3,
      image: "https://via.placeholder.com/400x300?text=Gaming+Console",
    },
    {
      id: 15,
      name: "Gaming Mouse",
      price: 755.94,
      category: "Gaming",
      rating: 4.7,
      image: "https://via.placeholder.com/400x300?text=Gaming+Mouse",
    },
    {
      id: 16,
      name: "Tablet",
      price: 151.86,
      category: "Electronics",
      rating: 2.3,
      image: "https://via.placeholder.com/400x300?text=Tablet",
    },
    {
      id: 17,
      name: "VR Headset",
      price: 888.65,
      category: "Wearables",
      rating: 4.8,
      image: "https://via.placeholder.com/400x300?text=VR+Headset",
    },
    {
      id: 18,
      name: "Bluetooth Speaker",
      price: 430.84,
      category: "Electronics",
      rating: 3.5,
      image: "https://via.placeholder.com/400x300?text=Bluetooth+Speaker",
    },
    {
      id: 19,
      name: "Air Conditioner",
      price: 482.72,
      category: "Home Appliances",
      rating: 2.4,
      image: "https://via.placeholder.com/400x300?text=Air+Conditioner",
    },
    {
      id: 20,
      name: "Fitness Tracker",
      price: 423.77,
      category: "Wearables",
      rating: 1.5,
      image: "https://via.placeholder.com/400x300?text=Fitness+Tracker",
    },
  ];
  